<?php
/**
 * Created by PhpStorm.
 * User: dennis
 * Date: 04.03.18
 * Time: 13:42
 */

namespace App\Command;


use App\Controller\TestController;
use PhpAmqpLib\Connection\AMQPStreamConnection;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Class ConsumeCommand
 * @package App\Command
 */
class ConsumeCommand extends Command {

    /**
     *
     */
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName("app:consume");
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $connection = new AMQPStreamConnection('localhost', 5672, 'guest', 'guest');
        $channel = $connection->channel();
        $channel->queue_declare(TestController::RABBITMQ_Q_NAME, false, false, false, false);
        $callback = function($message) {
            print_r(unserialize($message->getBody()));
        };

        $channel->basic_consume(TestController::RABBITMQ_Q_NAME, '', false, true, false, false, $callback);

        while(count($channel->callbacks)) {
            $channel->wait();
        }

        $channel->close();
        $connection->close();
    }
}